language: ruby
rvm:
- 2.7.2

services:
 - docker

before_install:
 - docker-compose up --build

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
 - bundle exec rubocop
