---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
securityDefinitions:
  JWT:
    description: the jwt for API auth
    type: apiKey
    name: Authorization
    in: header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
