# db/migrations/20201103204556_create_tools.rb

# frozen_string_literal: true

# This file way generated by Rails used by activerecord to generate versioning of database(postgres) table
class CreateTools < ActiveRecord::Migration[6.0]
  def change
    create_table :tools do |t|
      t.string :title
      t.string :link
      t.string :description
      t.string :tags, array: true
      t.string :created_by

      t.timestamps
    end
  end
end
